name: fast-forward merge
description: this action merges one branch into another without an extra merge conflict
branding:
  icon: 'git-merge'
  color: 'red'
inputs:
  to_branch:
    description: target branch
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ $GITHUB_REF }}
    - ${{ inputs.to_branch }}
